[target.riscv64gc-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=-crt-static",
    "-Clink-args=--sysroot=/sdk/host/riscv64-buildroot-linux-musl/sysroot",
    "-L", "../firmware/cviwrapper",
    "-L", "../firmware/feetech",
    "-L", "../firmware/tpu-sdk-sg200x/lib",
    "-L", "../firmware/duo-sdk/rootfs/usr/lib",
    "-L", "../models/tpu-mlir/lib",
    "-Clink-arg=-Wl,-rpath,../models/tpu-mlir/lib",
    "-Clink-arg=-Wl,-rpath,../firmware/tpu-sdk-sg200x/lib",
    "-Clink-arg=-Wl,-rpath,../firmware/duo-sdk/rootfs/lib",
    "-Clink-arg=-Wl,-rpath,../tpu-libs",
    "-Clink-arg=-Wl,-rpath,../sysroot/lib",
    "-Clink-arg=-Wl,-rpath,../sysroot/usr/lib",
]
linker = "/sdk/host/bin/riscv64-buildroot-linux-musl-gcc.br_real"
